### ISSUE TITLE
Incompatible with Charm

### ISSUE THREAD

**Issue by SplendidAlakey** [jaspersn/PortsParrotsPlus#1]
**MC** 1.17.1
**Fabric API** 0.37.0
**PortsParrotsPlus** 1.17.1-1.2.1
**Charm** fabric-1.17-3.3.2

Impossible to launch the game with both mods present. No crash log is being generated, but here is the log: [removed]. Removing either mod lets the game launch without any issues.

**Comment by jaspersn** [comment]
Fixed this incompatibility in version 1.2.2. Seemed to be a shared namespace issue.

**Comment by SplendidAlakey** [comment]
Can confirm, 1.2.2 fixed the issue. Thank you!
